# fly.toml app configuration file generated for basic-express-api-main-polished-hill-4595 on 2024-08-12T02:55:24+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'basic-express-api-main-polished-hill-4595'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3017
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
